config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"
  get "home/index"
  get "activity", to: "home#activity"
  get "analytics", to: "home#analytics"

  resources :enrollments do
    get :my_students, on: :collection
  end

  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons do
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [ :new, :create ]
  end
  resources :users, only: [ :index, :edit, :show, :update ]

  namespace :charts do
    get "users_per_day"
    get "enrollments_per_day"
    get "course_popularity"
    get "money_makers"
  end
  # es mejor tener un namespace que asi como abajo 
  # get "charts/users_per_day", to: "charts#users_per_day"
  # get "charts/enrollments_per_day", to: "charts#enrollments_per_day"
  # get "charts/course_popularity", to: "charts#course_popularity"
  # get "charts/money_makers", to: "charts#money_makers"


  # get "privacy_policy", to: "static_pages#privacy_policy"

  # get "up" => "rails/health#show", as: :rails_health_check

  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index
    @courses = Course.all.limit(4)
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews
    @latest = Course.latest.published.approved
    @top_rated = Course.top_rated.published.approved
    @popular = Course.popular.published.approved
    @purchased = Course.joins(:enrollments).where(enrollments: { user: current_user }).order(created_at: :desc).limit(3)
  end

  def activity
    if current_user.has_role?(:admin)
      @pagy, @activities =  pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else
      redirect_to root_path, alert: "Your are not authorized to access this page"
    end
  end

  def analytics
    if current_user.has_role?(:admin)
      # @enrollments = Enrollment.all
      # @courses = Course.all
    else
      redirect_to root_path, alert: "Your are not authorized to access this page"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def crud_label(key)
    case key
    when "create"
      "<i class='fa fa-plus'></i>".html_safe
    when "update"
      "<i class='fa fa-pen'></i>".html_safe
    when "destroy"
      "<i class='fa fa-trash'></i>".html_safe
    end
  end

  def model_label(model)
    case model
    when "Course"
      "<i class='fa fa-graduation-cap'></i>".html_safe
    when "Lesson"
      "<i class='fa fa-tasks'></i>".html_safe
    end
  end

end

app/views/home/activity.html.haml
-content_for :title do
  E-learning
  \|
  Activity

%h3.text-center 
  Activities
  .badge.bg-info
    = @activities.count

%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      -# = activity.id
      = activity.created_at.strftime( "%d-%m-%Y  %H:%m")
      (#{time_ago_in_words(activity.created_at)})
      = model_label(activity.trackable_type)
      = activity.trackable_type
      -# = activity.trackable_id
      - if activity.trackable_type == 'Lesson'
        - if Lesson.where(id: activity.trackable_id).present?
          = link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
        - else 
          Lesson was deleted
      - else
        = link_to activity.trackable, activity.trackable
      = activity.key
      = crud_label(activity.key.match(/\.(.*)/)[1])
      -# = activity.key.match(/\.(.*)/)[1]
      -# = activity.owner
      by
      = link_to activity.owner, user_path(activity.owner)
      - if activity.parameters.any?
        = activity.parameters

!= pagy_bootstrap_nav(@pagy)

app/views/home/analytics.html.haml
%h4
  Users created per day
= line_chart charts_users_per_day_path

%h4
  Enrollments created per day
-# = column_chart @enrollments.group_by_day(:created_at).count
= column_chart charts_enrollments_per_day_path

%h4
  Course popularity
-# = pie_chart @courses.group(:enrollments_count).count
-# = pie_chart @enrollments.joins(:course).group(:'courses.title').count


-# %h3
-#   Course popularity
-# = pie_chart @courses.group(:enrollments_count).count
-# = bar_chart @enrollments.joins(:course).group(:'courses.title').count
= bar_chart charts_course_popularity_path

%h4 
  Money paid courses
= bar_chart charts_money_makers_path

app/views/home/index.html.haml
-content_for :title do
  E-learning
  \|
  Online platform to learn

.p-5.mb-4.bg-body-tertiary.rounded-3
  .container-fluid.py-5
    .display-5.fw-bold
      What do you want to learn today?
    
    .p-4
    - if current_user
      .form-inline.align-self-center
        = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
          .input-group.input-group-sm
            = f.search_field :title_cont, class: "form-control-sm", placeholder: "Find a course", :autocomplete => :off
            %button.btn.btn-primary{:type => "submit"}
              %span.fa.fa-search{"aria-hidden" => "true"}
    

    -# This was before ransack gem
    -# .form-inline.align-self-center
    -#   = form_tag(courses_path, method: :get) do 
    -#     .input-group.input-group-sm
    -#       = text_field_tag :title, params[:title], autocomplete: "off", placeholder: "Search", class: "form-control"
    -#       %button.btn.btn-primary{:type => "submit"}
    -#         %span.fa.fa-search{"aria-hidden" => "true"}

.card-group
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule


- if current_user
  %hr
    %h2
      .fa.fa-user-graduate
      Continue Learning
    .row.row-cols-lg-4
      - @purchased.each do |course|
        .col
          = render 'courses/course', course: course
    .text-end
      = link_to 'All my purchased courses', purchased_courses_path
%hr
%h2
  .fa.fa-chart-line
  Popular Courses
.row.row-cols-lg-4
  - @popular.each do |course|
    .col
      = render 'courses/course', course: course
.text-end
  = link_to 'More popular courses', courses_path(courses_search: {s:'enrollments_count desc'})

%hr
%h2
  .fa.fa-star
  Top Rated Courses
.row.row-cols-lg-4
  - @top_rated.each do |course|
    .col
      = render 'courses/course', course: course
.text-end 
  = link_to 'Best rated courses', courses_path(courses_search: {s: 'average_rating desc'})

%hr
%h2
  .fa.fa-clock
  Latest Courses
.row.row-cols-lg-4
  - @latest.each do |course|
    .col
      = render 'courses/course', course: course
.text-end
  = link_to 'More new courses', courses_path(courses_search: {s: 'created_at desc' })
%hr
%h2
  .fa.fa-comment
  What our students have to say
.row.row-cols-lg-4
  - @latest_good_reviews.each do |enrollment|
    .col
      = render 'enrollments/enrollment', enrollment: enrollment

app/views/home/statistics.html.haml
%h3
  Users created per day
= line_chart @users.group_by_day(:created_at).count 

%h3
  Enrollments created per day
= column_chart @enrollments.group_by_day(:created_at).count

%h3
  Course popularity
-# = pie_chart @courses.group(:enrollments_count).count
-# = pie_chart @enrollments.joins(:course).group(:'courses.title').count


-# %h3
-#   Course popularity
-# = pie_chart @courses.group(:enrollments_count).count
= bar_chart @enrollments.joins(:course).group(:'courses.title').count