config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"
  get "home/index"
  get "activity", to: "home#activity"
  get "analytics", to: "home#analytics"

  resources :enrollments do
    get :my_students, on: :collection
  end

  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons do
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [ :new, :create ]
  end
  resources :users, only: [ :index, :edit, :show, :update ]

  namespace :charts do
    get "users_per_day"
    get "enrollments_per_day"
    get "course_popularity"
    get "money_makers"
  end
  # es mejor tener un namespace que asi como abajo 
  # get "charts/users_per_day", to: "charts#users_per_day"
  # get "charts/enrollments_per_day", to: "charts#enrollments_per_day"
  # get "charts/course_popularity", to: "charts#course_popularity"
  # get "charts/money_makers", to: "charts#money_makers"


  # get "privacy_policy", to: "static_pages#privacy_policy"

  # get "up" => "rails/health#show", as: :rails_health_check

  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  include RankedModel
  ranks :row_order, with_same: :course_id

  belongs_to :course, counter_cache: true
  has_many :user_lessons, dependent: :destroy
  # Course.find_each{ |course| Course.reset_counters(course.id, :lessons)}
  validates :title, :content, :course, presence: true
  validates :title, length: { maximum: 70 }
  validates_uniqueness_of :title, scope: :course_id

  has_rich_text :content
  has_one_attached :video
  has_one_attached :video_thumbnail
  validates :video,
    content_type: [ "video/mp4", "video/quicktime", "video/mpeg" ],
    size: { less_than: 50.megabytes, message: "size should be under 50 megabytes" }

  validates :video_thumbnail,
    content_type: [ "image/png", "image/jpg", "image/jpeg" ],
    size: { less_than: 500.kilobytes, message: "size should be under 500 kilobytes" }

  # Sirve para validar que existan thumbnail si hay video
  # validates :video_thumbnail, presence: true, if: :video_present?
  # def video_present?
  #   self.video.present?
  # end

  extend FriendlyId
  friendly_id :title, use: :slugged

  include PublicActivity::Model
  tracked owner: Proc.new { |controller, model| controller.current_user }
  # tracked

  def to_s
    title
  end

  def previous_lesson
    course.lessons.where("row_order < ?", row_order).order(:row_order).last
  end

  def next_lesson
    course.lessons.where("row_order > ?", row_order).order(:row_order).first
  end

  def viewed?(user)
    self.user_lessons.where(user: user).present?
    # self.user_lessons.where(user_id: [user.id], lesson_id: [self.id]).empty?
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy delete_video ]

  def index
    @lessons = Lesson.all
  end

  def show
    authorize @lesson
    current_user.view_lesson(@lesson)
    @lessons = @course.lessons.rank(:row_order)
  end

  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])
  end

  def edit
    authorize @lesson
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.friendly.find(params[:course_id])
    @lesson.course_id = @course.id
    authorize @lesson
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to [ @course, @lesson ], notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to [ @course, @lesson ], notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @lesson
    @lesson.destroy!

    respond_to do |format|
      format.html { redirect_to @course, status: :see_other, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_video
    authorize @lesson, :edit?
    @lesson.video.purge
    @lesson.video_thumbnail.purge 
    redirect_to edit_course_lesson_path(@course, @lesson), notice: "Video successfully deleted!"
  end

  def sort
    @course = Course.friendly.find(params[:course_id])
    lesson = Lesson.friendly.find(params[:lesson_id])

    authorize lesson, :edit?
    lesson.update(lesson_params)
    render body: nil
  end

  private
    def set_lesson
      @course = Course.friendly.find(params[:course_id])
      @lesson = Lesson.friendly.find(params[:id])
    end
    def lesson_params
      params.require(:lesson).permit(:title, :content, :row_order_position, :video, :video_thumbnail)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([@course, @lesson]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, input_html: { autocomplete: 'off' }
    = f.label :content
    = f.rich_text_area :content
    %small= f.error :content, class: "text-danger"
    %p 

    - if @lesson.video.attached?
      = @lesson.video.filename
      = link_to "Remove video and thumbnail", delete_video_course_lesson_path(@course, @lesson), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

    = f.input :video
    - if @lesson.video_thumbnail.attached?
      -# = image_tag @lesson.video_thumbnail, width: "200px"
      -# .row
      = @lesson.video_thumbnail.filename
    = f.input :video_thumbnail
    -# como estaba 
    -# = f.association :course
    -# Esto de abajo asigno el input del html por defecto si ya es un lesson o por params. as: :hidden hide the input
    -# = f.input :course_id, input_html: {value: @course.id || params[:course_id]}, as: :hidden

  .form-actions
    = f.button :submit, class: "btn-success"

app/views/lessons/_lesson.html.haml
.card
  .card-header
    - if lesson.viewed?(current_user)
      -# VIEWED
      .text-success.far.fa-check-square
    - else
      -# NOT VIEWED
      .text-danger.far.fa-check-square
    = link_to [@course, lesson] do
      %b #{lesson.row_order_rank + 1}.
      = lesson.title
  - if policy(lesson).show?
    .card-body
      -# = image_tag @lesson.video_thumbnail
      -if lesson.video.attached? && lesson.video.persisted?
        %video(controls="true" poster="#{ url_for lesson.video_thumbnail if lesson.video_thumbnail.attached? }" width="100%" preload="metadata")
          %source{src: rails_blob_url(lesson.video), type: "#{lesson.video.content_type}"}

      = lesson.content
  - if policy(lesson).edit?
    .card-footer
      = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning'
      = link_to 'Destroy', [@course, lesson], data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
  .card-footer
    - if lesson.previous_lesson
      .float-start
        = link_to course_lesson_path(@course, lesson.previous_lesson), class: 'btn btn-sm btn-info' do
          .fa.fa-arrow-left
          Previous
    - if lesson.next_lesson
      .float-end
        = link_to course_lesson_path(@course, lesson.next_lesson), class: 'btn btn-sm btn-info' do
          .fa.fa-arrow-right
          Next
%p
  

app/views/lessons/_lesson_preview.html.haml
- if policy(lesson).show?
  - if lesson.viewed?(current_user)
    .text-success.far.fa-check-square
  - else
    .text-danger.far.fa-check-square
- else 
  .fa.fa-check-square

= link_to [@course, lesson] do
  -# = lesson.row_order 
  %b #{lesson.row_order_rank + 1} 
  = lesson.title

.float-end
  - if policy(lesson).edit?
    = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', [@course, lesson], data: { turbo_method: :delete, turbo_confirm: 'Are you sure' }, class: 'btn btn-sm btn-danger'

app/views/lessons/edit.html.haml
-content_for :title do
  E-learning
  \/
  Course
  = @course.title
  \/
  Editing lesson
  = @lesson.title

= link_to 'Courses', courses_path
\/
= link_to @lesson.course.title, course_path(@course)
\/
= link_to @lesson.title, course_lesson_path(@course, @lesson)
\/
edit
%p

.card
  .card-header
    %h3
      .far.fa-check-square 
      Editing lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show', [@course, @lesson]
    \|
    = link_to 'Back to course', course_path(@course)

app/views/lessons/new.html.haml
-content_for :title do
  E-learning
  \/
  Course
  = @course.title
  \/
  New Lesson

= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
\/
new
%p

.card
  .card-header
    %h3
      .far.fa-check-square 
      New lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back to course', course_path(@course)

app/views/lessons/show.html.haml
-content_for :title do
  E-learning
  \/
  Course
  = @course.title
  \/
  Lesson
  = @lesson.title

= link_to 'Courses', courses_path
\/
= link_to @lesson.course.title, course_path(@course)
\/
= link_to @lesson.title, course_lesson_path(@course, @lesson)
%p

-# = @lesson.user_lessons.where(user: current_user).first.impression
.row 
  .col-lg-8
    = render 'lessons/lesson', lesson: @lesson
    %p
  .col-lg-4
    %ul.list-group
      %li.list-group-item 
        = link_to course_path(@course) do 
          .fa.fa-graduation-cap
          = @lesson.course.title
        .row
        .fa.fa-spinner
        = number_to_percentage(@course.progress(current_user), precision: 0)
      - @lessons.each do |lesson|
        - if @lesson.present? && @lesson == lesson
          %li.list-group-item.list-group-item-success
            = render "lessons/lesson_preview", lesson: lesson
        - else
          %li.list-group-item 
            = render "lessons/lesson_preview", lesson: lesson