config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"
  get "home/index"
  get "activity", to: "home#activity"
  get "analytics", to: "home#analytics"

  resources :enrollments do
    get :my_students, on: :collection
  end

  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons do
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [ :new, :create ]
  end
  resources :users, only: [ :index, :edit, :show, :update ]

  namespace :charts do
    get "users_per_day"
    get "enrollments_per_day"
    get "course_popularity"
    get "money_makers"
  end
  # es mejor tener un namespace que asi como abajo 
  # get "charts/users_per_day", to: "charts#users_per_day"
  # get "charts/enrollments_per_day", to: "charts#enrollments_per_day"
  # get "charts/course_popularity", to: "charts#course_popularity"
  # get "charts/money_makers", to: "charts#money_makers"


  # get "privacy_policy", to: "static_pages#privacy_policy"

  # get "up" => "rails/health#show", as: :rails_health_check

  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show ]
  before_action :set_course, only: %i[ show edit update destroy approve unapprove analytics ]

  # GET /courses or /courses.json
  def index
    # This was using the ILIKE in the first search header that we made, now with
    # ransack we dont need it
    # if params[:title]
    #   @courses = Course.where("title ILIKE ?",
    #     Course.sanitize_sql_like(params[:title]) + "%")
    # else
    #   # @courses = Course.all
    #   # for advance and the header search we remove this q and use ransack courses
    #   # @q = Course.ransack(params[:q])
    # end
    # rolify example:

    # if current_user.has_role?(:admin)
    #   @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    #   @courses = @ransack_courses.result.includes(:user)
    # else
    #   redirect_to root_path, alert: "You don have access"
    # end

    @ransack_path = courses_path
    @ransack_courses = Course.published.approved.ransack(params[:courses_search], search_key: :courses_search)
    # @courses = @ransack_courses.result.includes(:user)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
  end

  # GET /courses/1 or /courses/1.json
  def show
    authorize @course
    @lessons = @course.lessons.rank(:row_order)
    @enrollments_with_review = @course.enrollments.reviewed
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize @course
  end

  # GET /courses/1/edit
  def edit
    authorize @course
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def approve
    authorize @course, :approve?
    @course.update_attribute(:approved, true)
    redirect_to @course, notice: "Course approved and visible!"
  end

  def unapprove
    authorize @course, :approve?
    @course.update_attribute(:approved, false)
    redirect_to @course, notice: "Course unapproved and hidden!"
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def purchased
    @ransack_path = purchased_courses_path
    @ransack_courses = Course.joins(:enrollments).where(enrollments: { user: current_user }).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render "index"
  end

  def pending_review
    @ransack_path = pending_review_courses_path
    @ransack_courses = Course.joins(:enrollments).merge(Enrollment.pending_review.where(user: current_user)).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render "index"
  end

  def created
    @ransack_path = created_courses_path
    @ransack_courses = Course.where(user: current_user).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render "index"
  end

  def unapproved
    @ransack_path = unapproved_courses_path
    @ransack_courses = Course.unapproved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render "index"
  end

  def analytics
    authorize @course, :owner?
  end

  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_path, status: :see_other, notice: "Course was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to @course, alert: "Course has enrollments. Can not be destroyed."
    end
  end

  private
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:title, :description, :short_description, :price, :published, :language, :level, :avatar)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user
        link_to "You created this course. View analytics", course_path(course)
      elsif course.enrollments.where(user: current_user).any?
        link_to course_path(course) do
          "You bought this course. Keep learning"
          "<i class='fa fa-spinner'></i>".html_safe + " " +
          number_to_percentage(course.progress(current_user), precision: 0)
        end
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: "btn btn-md btn-success"
      else
        link_to "Free", new_course_enrollment_path(course), class: "btn btn-md btn-success"
      end
    else
      link_to "Check price", new_course_enrollment_path(course), class: "btn btn-md btn-success"
    end
  end

  def review_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if user_course.pending_review.any?
          link_to edit_enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + "" +
            "<i class='text-dark fa fa-question'></i>".html_safe + "" +
            "Add a review"
          end
        else
          link_to enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + "" +
            "<i class='text-dark fa fa-check'></i>".html_safe + "" +
            "Thanks for reviewing! Your Review"
          end
        end
      end
    end
  end
end

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  -if course.avatar.attached?
    .card-img-top
      = image_tag course.avatar, height: "200px", width: "100%"
      -# = image_tag course.avatar.variant(resize_to_limit: [100, 100])
  .card-body
    %small= simple_format(course.short_description)
  .card-footer
    .text-center
      = enrollment_button(course)
      .row
      = review_button(course)
  .card-footer
    .row
      .col-md-6
        .text-warning.fa.fa-star
        %b= course.average_rating
        -# Enrollments count:
        -# = course.enrollments.count
        -# Counter cache enrollments count:
        (
        .fa.fa-user-graduate
        = course.enrollments_count
        )
        .fa.fa-list-check
        = course.lessons_count
      .col-md-6
        .text-end
          .fa.fa-chalkboard-teacher
          = link_to course.user.username, user_path(course.user)
  -# .card-footer
  -#   .fa.fa-list-check
  -#     = course.lessons_count
  -# .card-footer
  -#   .row
  -#     .col-md-6
  -#       .fa.fa-globe-africa
  -#       = course.language
  -#     .col-md-6
  -#       .text-end
  -#         .fa.fa-signal
  -#         = course.level
  -# .card-footer
  -#   .row
  -#     .col-md-6
  -#       .fa.fa-clock
  -#       = course.created_at.strftime('%d-%b-%Y')
  -#     .col-md-6
  -#       .text-end
  -#         .fa.fa-chalkboard-teacher
  -#         = link_to course.user.username, user_path(course.user)
  - if current_user
    - if policy(course).owner?
      .card-footer
        = link_to "Add lesson", new_course_lesson_path(course, @lesson), class: 'btn btn-sm btn-primary'
        = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
        - if policy(course).destroy?
          = link_to 'Destroy', course, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
        = link_to analytics_course_path(course), class: 'btn btn-sm btn-info' do
          .fa.fa-chart-bar
          Analytics

    - if policy(course).admin_or_owner?
      .card-footer
        - if course.published?
          .badge.bg-success published
        - else
          .badge.bg-danger unpublished
        - if course.approved?
          .badge.bg-success approved
        - else
          .badge.bg-danger unapproved
    - if policy(course).approve?
      .card-footer
        - if course.approved?
          = link_to "unapprove", unapprove_course_path(course), data: { turbo_method: :patch }, class: 'btn btn-sm btn-danger'
        - else
          = link_to "approve", approve_course_path(course), data: { turbo_method: :patch }, class: 'btn btn-sm btn-success'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    -# = f.label :avatar
    .row
    - if @course.avatar.attached? && @course.avatar.persisted?
      = image_tag @course.avatar, width: "200px"
      -# = @course.avatar.content_type
      -# = @course.avatar.key
      -# = @course.avatar.metadata
    .row
    = @course.avatar.filename
    .row
    -# = f.file_field :avatar
    -# %small= f.error :avatar, class: "text-danger"
    = f.input :avatar
    .row
    = f.label :description
    = f.rich_text_area :description, data: {controller: "trix"}
    %small= f.error :description, class: "text-danger"
    = f.input :short_description
    = f.input :language, collection: Course.languages, include_blank: true
    = f.input :level, collection: Course.levels, include_blank: true
    = f.input :price
    = f.input :published

  .form-actions
    = f.button :submit, class: "btn-success"

app/views/courses/analytics.html.haml
-content_for :title do
  E-learning
  \|
  = @course.title
  Analytics

= link_to 'Courses', courses_path
\/ 
= link_to course_path(@course) do
  .fa.fa-graduation-cap
  = @course.title
\/ 
= link_to analytics_course_path(@course) do
  .fa.fa-chart-bar
  Analytics

%h4.text-center
  Analytics for #{@course.title}

Enrollments per day, quantity
= line_chart @course.enrollments.group_by_day(:created_at).count

Enrollments per day, revenue
= line_chart @course.enrollments.group_by_day(:created_at).sum(:price)

Unique user views(how many unique users viewed the lesson)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').count

Impressions per lesson (how many times the lesson was opened)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').sum(:impression)

app/views/courses/edit.html.haml
-content_for :title do
  E-learning
  \|
  Editing
  = @course.title

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      Editing course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show', @course
    \|
    = link_to 'Back', courses_path

app/views/courses/index.html.haml
- content_for :title do
  E-learning
  \|
  = action_name.humanize
  courses

%h3.text-center 
  = action_name.humanize
  courses
  .badge.bg-info
    = @courses.count

.row
  .col-md-2
    %form.row.align-items-center.my-3
      -# = search_form_for @q do |f|
      = search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f|
        = f.label :title
        = f.search_field :title_cont, placeholder: "Title", class: 'form-control'
        = f.label :description
        = f.search_field :short_description_cont, placeholder: "Description", class: 'form-control'
        = f.label :language
        = f.select :language_cont, Course.languages, include_blank: true
        = f.label :level
        = f.select :level_cont, Course.levels, include_blank: true
        = f.label :teacher
        = f.search_field :user_email_cont, placeholder: "Email", class: 'form-control'
        = sort_link(@ransack_courses, :price)
        = sort_link(@ransack_courses, :average_rating, "Top Rated")
        = sort_link(@ransack_courses, :enrollments_count, "Most Popular")
        = sort_link(@ransack_courses, :created_at, "Fresh")

        %p
        = f.submit class: "btn btn-sm btn-secondary form-control"
        %p
        = link_to @ransack_path, class: "btn btn-sm btn-secondary form-control" do
          .fa.fa-refresh
  .col-md-10
    .row.row-cols-lg-4
      - @courses.each do |course|
        .col
          = render 'courses/course', course: course
    -# != pagy_nav(@pagy)
    != pagy_bootstrap_nav(@pagy)
%br

app/views/courses/new.html.haml
-content_for :title do
  E-learning
  \|
  New Course

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      New course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back', courses_path

app/views/courses/show.html.haml
- content_for :title do
  E-learning
  \|
  = @course.title

= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
%p
.row
  .col-lg-8.order-1.order-lg-0
    .py-5.px-3.mb-4.bg-body-tertiary.rounded-3
      .container-fluid
        %h3
          .fa.fa-graduation-cap
          = @course.title
          -# .row
          -# -# = @course.avatar.attached?
          -# - if @course.avatar.attached?
          -#   = image_tag @course.avatar, width: "200px"
        .p-3
        .row
        .fa.fa-clock
        = @course.updated_at.strftime("%b/%Y")
        .row
        .fa.fa-globe-africa
        = @course.language
        .row
        .fa.fa-signal
        = @course.level
        .p-3
        = @course.description
    %h4
      .fa.fa-tasks
      = pluralize(@course.lessons_count, 'lesson')
      .float-end
        .fa.fa-spinner
        = number_to_percentage(@course.progress(current_user), precision: 0)
    %ul.list-group#sortable{data: { controller: "sortable" }}
      - @lessons.each do |lesson|
        %li.list-group-item{data: {sortable_handle: "", sortable_id: lesson.row_order_rank + 1, sortable_model: lesson.class, sortable_update_url: course_lesson_sort_path(@course, lesson) }}
          = render "lessons/lesson_preview", lesson: lesson
    %p

      %h4
      .fa.fa-comment
      = pluralize(@enrollments_with_review.count, 'review')
    
    - @enrollments_with_review.each do |enrollment|
      = render 'enrollments/enrollment', enrollment: enrollment
      %p 

  .col-lg-4.order-0.order-lg-1
    .sticky-top
      = render 'courses/course', course: @course
    %p