config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"
  get "home/index"
  get "activity", to: "home#activity"
  get "analytics", to: "home#analytics"

  resources :enrollments do
    get :my_students, on: :collection
  end

  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons do
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [ :new, :create ]
  end
  resources :users, only: [ :index, :edit, :show, :update ]

  namespace :charts do
    get "users_per_day"
    get "enrollments_per_day"
    get "course_popularity"
    get "money_makers"
  end
  # es mejor tener un namespace que asi como abajo 
  # get "charts/users_per_day", to: "charts#users_per_day"
  # get "charts/enrollments_per_day", to: "charts#enrollments_per_day"
  # get "charts/course_popularity", to: "charts#course_popularity"
  # get "charts/money_makers", to: "charts#money_makers"


  # get "privacy_policy", to: "static_pages#privacy_policy"

  # get "up" => "rails/health#show", as: :rails_health_check

  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/layouts/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        = Time.now.year
        CoursePlatform Sp. z o.o.
        .row
        .fa.fa-envelope
        = mail_to 'david@example.com'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        = link_to 'Teach on EDURGE', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to "Rubygems", root_path, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.me-auto
        %li.nav-item{class: "#{'fw-bold' if current_page?(root_path)}"}
          = link_to root_path, class: "nav-link" do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'fw-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: "nav-link" do
            .fa.fa-graduation-cap
            Courses

        .form-inline.align-self-center
          = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
            .input-group.input-group-sm
              = f.search_field :title_cont, class: "form-control-sm", placeholder: "Find a course", :autocomplete => :off
              %button.btn.btn-primary{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}
        -# %li.nav-item{class: "#{'fw-bold' if current_page?(new_course_path)}"}
        -#   = link_to new_course_path, class: "nav-link" do
        -#     .fa.fa-plus
        -#     New Course
        -# %li.nav-item{class: "#{'fw-bold' if current_page?(users_path)}"}
        -#   = link_to users_path, class: "nav-link" do
        -#     .fa.fa-users
        -#     Users
        -# %li.nav-item{class: "#{'fw-bold' if current_page?(enrollments_path)}"}
        -#   = link_to enrollments_path, class: "nav-link" do
        -#     .fa.fa-lock-open
        -#     Enrollments

      %ul.navbar-nav.me-auto
        - if current_user.has_role?(:student)
          %li.nav-item.dropdown
            %a#studentDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-graduation-cap
              Learn
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "studentDropdown"}
              = link_to purchased_courses_path, class: "dropdown-item" do
                .fa.fa-graduation-cap
                Purchased Courses
                .badge.bg-danger
                  = current_user.enrollments_count
              = link_to pending_review_courses_path, class: "dropdown-item" do
                .fa.fa-star
                Pending Review
                .badge.bg-danger
                  = current_user.enrollments.pending_review.count


        - if current_user.has_role?(:teacher)
          %li.nav-item.dropdown
            %a#teacherDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-chalkboard-teacher
              Teacher
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "teacherDropdown"}
              = link_to new_course_path, class: "dropdown-item" do
                .fa.fa-graduation-cap
                .fa.fa-plus
                New Course
              = link_to created_courses_path, class: "dropdown-item" do
                .fa.fa-graduation-cap
                Created Courses
                .badge.bg-danger
                  = current_user.courses_count
              = link_to my_students_enrollments_path, class: "dropdown-item" do
                .fa.fa-graduation-cap
                My Students
                .badge.bg-danger
                  = Enrollment.joins(:course).where(courses: {user: current_user}).count

        - if current_user.has_role?(:admin)
          %li.nav-item.dropdown
            %a#adminDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-cog
              Admin
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "adminDropdown"}
              = link_to users_path, class: "dropdown-item" do
                .fa.fa-users
                Users
                .badge.bg-danger
                  = User.count
              = link_to unapproved_courses_path, class: "dropdown-item" do
                .fa.fa-graduation-cap
                Unapproved Courses
                .badge.bg-danger
                  = Course.unapproved.count
              = link_to enrollments_path, class: "dropdown-item" do
                .fa.fa-lock-open
                Enrollments
                .badge.bg-danger
                  = Enrollment.count
              = link_to activity_path, class: "dropdown-item" do
                .fa.fa-bell
                Activity
              = link_to analytics_path, class: "dropdown-item" do
                .fa.fa-pie-chart
                Analytics

    
      -# .form-inline.align-self-center 
      -#   = form_tag(courses_path, method: :get) do 
      -#     .input-group.input-group-sm
      -#       = text_field_tag :title, params[:title], autocomplete: "off", placeholder: "Search", class: "form-control"
      -#       %button.btn.btn-primary{:type => "submit"}
      -#         %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.me-right  
        -# %li.nav-item{class: "#{'fw-bold' if current_page?(activity_path)}"}
        -#   = link_to activity_path, class: "nav-link" do
        -#     .fa.fa-bell
        -#     Activity
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, class: "dropdown-item", data: { turbo_method: "delete" } do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item
          = link_to "Sign Up", new_user_registration_path, class: "nav-link"
        %li.nav-item
          = link_to "Log In", new_user_session_path, class: "nav-link"

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - alert_class = name.to_s == 'notice' ? 'success' : 'danger'
    .alert{:class => ["alert-#{alert_class}",'alert-dismissible', 'fade', 'show']}
      = msg
      .button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = content_for?(:title) ? yield(:title) : "E-learning"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/manifest.json", :rel => "manifest"}/
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
      = yield
    %br
    .bg-info
      = render 'layouts/footer'